

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: -> # optional
          CODE_LANG: rust # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: true # optional
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          COMMITTER_NAME: GitHubActionBot # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
          AUTHOR_NAME: jee # optional
          AUTHOR_EMAIL: jeecoding09@gmail.com


          # -- Old variant
          # SHOW_TITLE: "true" 
          # BLOCKS: "->" 
          # SHOW_SHORT_INFO: "true"
          # SHOW_PROFILE_VIEWS: "true"
          # TIME_RANGE: "last_30_days"
          # SHOW_OS: "false"
          # SHOW_LANGUAGE: "true"
          # SHOW_EDITORS: "false"
          # SHOW_LANGUAGE_PER_REPO: "false"
          # SHOW_PROJECTS: "false"
          # SHOW_LOC_CHART: "false"
          # SHOW_TIMEZONE: "false"
          # COMMIT_USERNAME: Jee
          # SHOW_MASKED_TIME: "false"
          # SHOW_AI_CODE: "false"
          # SHOW_AI_STATS: "false"
         
